[package]
name = "RustProject"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0"
toml = "0.8"

tokio = {version = "1", features = ["full"]}
tokio-postgres = "0.7.16"

[profile.release]
debug = true
